### ISSUE TITLE
Creating six-question 'mini' version of the tool. 

### ISSUE THREAD

**Issue by thomwithoutanh** [the-engine-room/alidade#12]
[Finalised content to come and Ozren hasn't designed this yet] 

Idea is to have a page for people who will never complete the whole tool, and are prepared to spend max 10 mins on the site. So, the page would give them:
- Six rules (ie the rules of thumb) accompanied by six questions
- It would look like: 
 - six text entry fields on a single page, with accompanying text
 - ideally (not essential) an output at the bottom with their six answers that they can download - PDF and/or Word. 

I wasn't thinking of this as something that would need a user to set up an account to use - it would all be done in one page. 

Let me know how complex this is and we can talk more about what's actually possible?

**Comment by IronRunes** [comment]
#33
