### ISSUE TITLE
Risk of user losing content 

### ISSUE THREAD

**Issue by thomwithoutanh** [the-engine-room/alidade#28]
@IronRunes @OzrenMuic 

Having played around with it for a bit and started to add content, I noticed one potential problem with the new UX.

If the user enters text into a slide and then navigate to another slide by clicking the sidebar rather than the 'next' button, none of the content they have entered will be saved. 

I can imagine people losing content in this way (the sidebar is in some ways quite an attractive way of moving around).

I'm not sure what the obvious solution to this is.

**Comment by thomwithoutanh** [comment]
@OzrenMuic Alan and I talked about this. 

Apparently there is no real way around the fact that people need to click 'next' to save their content. 

I think we just have to make this very clear in the instructions when they are using the tool. Suggestion: we add text underneath the 'next' box that says: 

"Click to save your progress"

**Comment by IronRunes** [comment]
refer to #31
