### ISSUE TITLE
Allow user to move between slides by clicking on the progress bar

### ISSUE THREAD

**Issue by thomwithoutanh** [the-engine-room/alidade#3]

**Comment by IronRunes** [comment]
I built this, but it would be good to go over it and check if it's working as desired. Give it a go on the staging server, https://tsa.zardtech.com

**Comment by thomwithoutanh** [comment]
@IronRunes Looks great!
One additional request - could it show the slide title (1.1, 1.2 etc) on mouseover? _Note that the slide titles are different on the staging version, so it would show a full-text title like 'what do you want the tool to do?' there._

**Comment by thomwithoutanh** [comment]
@IronRunes Looks brill. Could you implement this on the production version by early next week? Thanks :smile:
